### ISSUE TITLE
Feature: Add a BagIt Bag creation activity

### ISSUE THREAD

**Issue by djjuhasz** [artefactual-sdps/temporal-activities#11]
**Is your feature request related to a problem? Please describe.**

Enduro needs to create a BagIt Bag at one of a few points in the preservation workflow:

1. If a pre-processing child workflow is run, then the final SIP produced by pre-processing must be delivered in a Bag (https://github.com/artefactual-sdps/enduro/issues/805#issuecomment-1979881409)
2. If a pre-processing child workflow is not run, then the Enduro processing workflow must Bag the transfer contents before delivering the SIP to the preservation system (https://github.com/artefactual-sdps/enduro/issues/805#issuecomment-2040656506)

Using BagIt as the specification for SIPs produced by Enduro provides an extensible, standards based way to exchange preservation data and metadata with built-in file and package integrity checks.

**Describe the solution you'd like**

Add a new activity to create a BagIt Bag from a source directory, which can be imported into Enduro and SDPS prepocessing Temporal workflows as needed.

**Describe alternatives you've considered**

1. A unique implementation of a Bag creation activity in each of the different projects that need it. This option requires a higher maintenance cost due to redundancies in the various implementations and a higher cognitive load for developers due to the variations in implementation.
2. Creating SIPs using an alternative standard, e.g. [Archivematica Standard Transfer (AMST)](https://www.archivematica.org/en/docs/archivematica-1.15/user-manual/transfer/transfer/#transfer-types) (this is the status quo for Enduro), [E-ARK SIP](https://earksip.dilcis.eu/).  Archivematica already accepts BagIt and AMSTs, a3m only accepts AMSTs.  Implementing a third data exchange standard for SIPs, such as E-ARK SIP, would require development in Archivematica, a3m, and Enduro to facilitate exchange between these systems. AMST is single vendor (but open), "de facto" standard without a formal specification.

**Additional context**

There are three different Bag creation options I'm considering for the implementation:

1. [bagit-python](https://github.com/LibraryOfCongress/bagit-python). Pros: developed by the Library of Congress, very mature project, lots of features (including Bag creation, updating, and validation), we use it in Archivematica & a3m. Cons: Python (extra deployment requirements, poor integration with Go), very little development in recent years (maintenance mode).
2. [go-bagit](https://github.com/nyudlts/go-bagit). Pros: Go (fewer deployment requirements, excellent integration with Go); Bag creation, validation, and modification. Cons: Alpha version (not intended for production), not well supported or maintained, has some bugs, not 100% standards compliant.  We may need to fork the project to add features we need and fix bugs quickly, which will require maintenance time and effort.
3. Build our own Go Bag creation package. Pros: All the pros of option 2, we can build it exactly the way we want to (greenfield), smaller package (easier to maintain and understand). Cons: All of the cons of option 2, no Bag validation or modification (unless we build that too), we take on 100% of the maintenance burden.

**Comment by djjuhasz** [comment]
@fiver compiled a more in-depth list of the BagIt bag software available: https://docs.google.com/document/d/1XYjAlvxaquZiWqt_KdeuPhg6nXxpvHuFybm8dV7cYrg/edit

**Comment by djjuhasz** [comment]
We've decided to go with a blended solution:

1. Use https://github.com/nyudlts/go-bagit for Bag creation.  We may fork the repo to allow us to incorporate bug fixes and enhancements into this project quickly.  Bag creation seems like a much simpler use case then validation, because validation has to handle a wide variety of Bag types, so this seems like a good fit for a newer implementation like go-bagit.
2. Use https://github.com/LibraryOfCongress/bagit-python for Bag validation (which is another activity we will need in the future).  The maturity of bagit-python makes us more confident that it can validate a wide range of Bag types correctly.  We may use an embedded version of the Python interpreter (e.g. https://github.com/artefactual-labs/bagit-gython) to avoid the need to add Python and Python libraries (pip, packages) to our deployment dependencies.

**Comment by djjuhasz** [comment]
Commit 0d1f5defd5659e1297bc24a665a6f359da790246 added the `bagit.CreateBagActivity` for creating bags.

I've opened issue #19 for implementing a complimentary `bagit.ValidateBagActivity`.

**Comment by fiver-watson** [comment]
Can confirm that AIP is bagged at end of workflow. 

Not sure if this is part of Archivematica or what, but I noticed there are a lot of extra subdirs added for the metadata files? For example metadata files were in: 

```
little_vecteur_sip-9a68c349-98fc-4b39-91b4-0eff2d306da3/data/objects/metadata/transfers/little_vecteur_sip-d2e0c42d-8166-40d8-8ff7-34c865b2b6e9
```

Expected that to be `little_vecteur_sip-9a68c349-98fc-4b39-91b4-0eff2d306da3/data/objects/metadata` ? Perhaps @sallain can tell me if this is just an AM thing...

**Comment by sallain** [comment]
It's just an AM thing :sparkles: The reason that it's in a transfer subdirectory is because of Archivematica's backlog/arrangement functionality - since these metadata files came from the original transfer, they're sequestered in case a user uses the arrangement feature to combine multiple transfers. If that had happened, you'd see multiple directories in the transfers dir, each representing a discrete transfer that had been combined. This lets Archivematica maintain multiple metadata.csv files, for example, when combining transfers.

**Comment by fiver-watson** [comment]
okeeee, then considered done!

**Comment by sallain** [comment]
I was able to download a PIP that had been bagged but not yet processed through Archivematica, and it was valid and well-formed.
